#!/bin/sh
# Shells are made of dicks.
if [ -z ${DISTROEXEC} ]; then
	SOURCED=0
else
	SOURCED=1
fi

DISTROSCRIPT="0.13"

getkernel() {
	if [ "${OS}" = "AIX" ]; then
		KERNEL=$(oslevel)
	else
		KERNEL=$(uname -r)
	fi
	export KERNEL
	return 0
}

getdistro() {
	if [ "${OS}" = "Linux" ]; then
		if [ -f /etc/redhat-release ]; then
			DISTRO=$(cat /etc/redhat-release | awk '{print $1}')
			if [ "${DISTRO}" = "Red" ]; then
				DISTRO="RedHat"
			fi
		elif [ -f /etc/mandriva-release ]; then
			DISTRO="Mandriva"
		elif [ -f /etc/arch-release ]; then
			DISTRO="ArchLinux"
		elif [ -f /etc/SuSE-release ]; then
			DISTRO="SuSE"
		elif [ -f /etc/mandrake-release ]; then
			DISTRO="Mandrake"
		elif [ -f /etc/debian_version ]; then
			# shit based on debian
			if [ -f /etc/mailcleaner/etc/mailcleaner/version.def ]; then
				DISTRO="MailCleaner"
			else
				DISTRO="Debian"
			fi
		elif [ -f /etc/UnitedLinux-release ]; then
			DISTRO="UnitedLinux"
		else
			DISTRO=$(lsb_release -si 2>/dev/null)
		fi
		if [ -z "${DISTRO}" ]; then
			DISTRO="Unknown"
		fi
	elif [ "${OS}" = "FreeBSD" ]; then
		if [ -f /etc/platform -a -f /etc/version ]; then
			DISTRO="pfSense"
		elif [ -f /usr/local/bin/pbreg ]; then
			DISTRO="PC-BSD"
		elif [ -f /tmp/freenas_config.md5 ]; then
			DISTRO="FreeNAS"
		else
			DISTRO=
		fi
	elif [ "${OS}" = "Solaris" ]; then
		DISTRO=$(head -n 1 /etc/release | awk '{print $1}')
	else
		DISTRO=
	fi
	export DISTRO
	return 0
}

getarch() {
	if [ "${OS}" = "Solaris" ]; then
		if [ $(isainfo | grep -c amd64) -eq 1 ]; then
			ARCH="amd64"
		else
			ARCH=$(isainfo)
		fi
	else
		ARCH=$(uname -m)
	fi
	if [ "${OS}" = "Linux" ]; then
		if [ "${ARCH}" = "x86_64" ]; then
			ARCH="amd64"
		fi
	fi
	export ARCH
	return 0
}

getversion() {
	if [ "${OS}" = "AIX" ]; then
		VERSION=$(oslevel -r)
	elif [ "${OS}" = "FreeBSD" ]; then
		if [ "${DISTRO}" = "pfSense" ]; then
			VERSION=$(cat /etc/version)
		elif [ "${DISTRO}" = "PC-BSD" ]; then
			VERSION=$(pbreg get /PC-BSD/Version)
		else
			VERSION=$(uname -i)
		fi
	elif [ "${OS}" = "OpenBSD" ]; then
		VERSION=$(uname -v)
	elif [ "${OS}" = "Linux" ]; then
		if [ -f /etc/redhat-release ]; then
			VERSION=$(cat /etc/redhat-release | sed 's/.*release\ //' | sed 's/\ .*//')
		else
			VERSION=$(lsb_release -ri 2>/dev/null)
		fi
	fi
	export VERSION
	return 0
}

if [ -z ${DISTROEXEC} ]; then
	case $(uname -s) in
		Linux)
			OS="Linux"
			getkernel
			getarch
			getdistro
			getversion
			;;
		SunOS)
			OS="Solaris"
			getkernel
			getarch
			getdistro
			getversion
			;;
		FreeBSD)
			OS="FreeBSD"
			getkernel
			getarch
			getdistro
			getversion
			;;
		OpenBSD)
			OS="OpenBSD"
			getkernel
			getarch
			getversion
			;;
		AIX)
			OS="AIX"
			getkernel
			getversion
			;;
		*)
			# No idea what it is, kill them with fire
			echo "Unsupported"
			exit 1
	esac

	echo "${OS}|${KERNEL}|${ARCH}|${DISTRO}|${VERSION}"
	exit 0
fi
